services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./db_data/data.db:/backend/Response.db  # Map local folder for database
    networks:
      - app-network

  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP for Let's Encrypt challenges
      - "443:443"  # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
    
